name = "texty-backend"
main = "src/worker.ts"
compatibility_date = "2025-03-25"

[durable_objects]
bindings = [
  { name = "TEXT_DO", class_name = "TextDurable" },
  { name = "INDEX_DO", class_name = "IndexDurable" }
]

[[migrations]]
tag = "v1"
new_classes = ["HelloDurable"]

[[migrations]]
tag = "v2"
new_classes = ["TextDurable"]

[[migrations]]
tag = "v3"
new_classes = ["IndexDurable"]
