name = "texty-backend"
main = "src/worker.ts"
compatibility_date = "2025-03-25"

[durable_objects]
bindings = [
  { name = "TEXT_DO", class_name = "TextDurable" }
]

# Keep the original migration that created HelloDurable
[[migrations]]
tag = "v1"
new_classes = ["HelloDurable"]

# Add TextDurable in a new migration
[[migrations]]
tag = "v2"
new_classes = ["TextDurable"]

# We'll add a delete migration for HelloDurable later
# after ensuring all data is migrated
