name = "texty-backend"
main = "src/worker.ts"
compatibility_date = "2025-03-25"

[durable_objects]
bindings = [
  { name = "HELLO_DO", class_name = "HelloDurable" }
]

# This is your initial Durable Object migration, required so Wrangler knows to create it.
[[migrations]]
tag = "v1"
new_classes = ["HelloDurable"]
